# Generated by Django 5.0.14 on 2026-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('level_name', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
    ]
