# Generated by Django 5.0.14 on 2026-09-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_package_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ryutubevideo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ryutubevideo',
            name='linked_course',
        ),
        migrations.DeleteModel(
            name='RyutubeCategory',
        ),
        migrations.DeleteModel(
            name='RyutubeVideo',
        ),
    ]
