# Generated by Django 5.0.14 on 2026-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_ryutubevideo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ไฟล์เอกสารประกอบการเรียน (PDF)', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_title',
            field=models.CharField(blank=True, help_text='ชื่อเอกสารแนบ (เช่น เอกสารประกอบการเรียน N5)', max_length=255, null=True),
        ),
    ]
