# Generated by Django 5.0.14 on 2026-08-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipBlacklistPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('amount', 'Amount'), ('name', 'Name'), ('keyword', 'Keyword')], default='keyword', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'slip_blacklist_patterns',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('level_access', models.CharField(blank=True, max_length=50, null=True)),
                ('is_zoom_included', models.BooleanField(default=True)),
                ('slip_path', models.TextField(blank=True, help_text='AES-256 encrypted file path', null=True)),
                ('trans_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='SlipVerificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspicious', 'Suspicious')], default='pending', max_length=20)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_account', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.TextField(blank=True, help_text='JSON payload from EasySlip API', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='payments.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='slip_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slip_verification_logs',
            },
        ),
    ]
