# Generated by Django 5.0.14 on 2026-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverificationcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_remark',
            field=models.TextField(blank=True, help_text='บันทึกข้อความจาก Admin', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_renewal_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ราคาต่ออายุเฉพาะบุคคล', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, help_text='คะแนนสะสม / Reward Points'),
        ),
    ]
