# Generated by Django 5.0.14 on 2026-09-11 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AraigoguSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('target_language', models.CharField(choices=[('TH', 'Thai'), ('JA', 'Japanese'), ('ZH', 'Chinese')], default='JA', max_length=10)),
                ('mode', models.CharField(choices=[('chat', 'Chat Tutor'), ('checker', 'Grammar Checker'), ('interview', 'Interview Practice')], default='chat', max_length=30)),
                ('title', models.CharField(default='บทสนทนาใหม่', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='araigogu_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'araigogu_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AraigoguMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.araigogusession')),
            ],
            options={
                'db_table': 'araigogu_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('triggered_action', models.CharField(choices=[('FREE_COURSE', 'Free Course'), ('REGISTER', 'Register'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_logs',
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='GREETING', max_length=50)),
                ('selected_course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_package', models.CharField(blank=True, max_length=50, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temp_user_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_sessions',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='หมวดหมู่ เช่น วิดีโอ, การจ่ายเงิน, ควิซ', max_length=100)),
                ('message', models.TextField(help_text='รายละเอียดปัญหา')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
    ]
