# Generated by Django 5.0.14 on 2026-09-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('QNA', '❓ สอบถามภาษาญี่ปุ่น'), ('TECHNIQUE', '💡 แชร์เทคนิคการเรียน'), ('JAPAN_EXP', '✈️ ประสบการณ์ญี่ปุ่น'), ('GENERAL', '🎌 พูดคุยทั่วไป')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('original_content', models.TextField(blank=True, help_text='Original content before AI moderation rewrite', null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('moderation_status', models.CharField(choices=[('APPROVED', '✅ ผ่านการอนุมัติ'), ('REWRITTEN', '✨ ปรับแต่งโดย AI'), ('REJECTED', '❌ ไม่อนุญาตให้โพสต์')], default='APPROVED', max_length=20)),
                ('moderation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('original_content', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('APPROVED', '✅ ผ่านการอนุมัติ'), ('REWRITTEN', '✨ ปรับแต่งโดย AI'), ('REJECTED', '❌ ไม่อนุญาตให้โพสต์')], default='APPROVED', max_length=20)),
                ('moderation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.post')),
            ],
            options={
                'db_table': 'community_post_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_post_likes',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
